// <copyright file="Leaderboards.cs" company="Jan Ivar Z. Carlsen, Sindri Jóelsson">
// Copyright (c) 2016 Jan Ivar Z. Carlsen, Sindri Jóelsson. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.
// </copyright>

namespace CloudOnce
{
    using System.Collections.Generic;
    using Internal;

    /// <summary>
    /// Provides access to leaderboards registered via the CloudOnce Editor.
    /// This file was automatically generated by CloudOnce. Do not edit.
    /// </summary>
    public static class Leaderboards
    {
        private static readonly UnifiedLeaderboard s_speedyLeaderboard = new UnifiedLeaderboard("SpeedyLeaderboard",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            "com.speedy.leaderboard"
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkI-r_H8-cIEAIQAQ"
#else
            "SpeedyLeaderboard"
#endif
            );

        public static UnifiedLeaderboard SpeedyLeaderboard
        {
            get { return s_speedyLeaderboard; }
        }

        private static readonly UnifiedLeaderboard s_bombyLeaderboard = new UnifiedLeaderboard("BombyLeaderboard",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            "com.bomby.leaderboard"
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkI-r_H8-cIEAIQAg"
#else
            "BombyLeaderboard"
#endif
            );

        public static UnifiedLeaderboard BombyLeaderboard
        {
            get { return s_bombyLeaderboard; }
        }

        private static readonly UnifiedLeaderboard s_shapeshiftyLeaderboard = new UnifiedLeaderboard("ShapeshiftyLeaderboard",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            "com.shapeshifty.leaderboard"
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkI-r_H8-cIEAIQBA"
#else
            "ShapeshiftyLeaderboard"
#endif
            );

        public static UnifiedLeaderboard ShapeshiftyLeaderboard
        {
            get { return s_shapeshiftyLeaderboard; }
        }

        private static readonly UnifiedLeaderboard s_ninjyLeaderboard = new UnifiedLeaderboard("NinjyLeaderboard",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            "com.ninjy.leaderboard"
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkI-r_H8-cIEAIQBQ"
#else
            "NinjyLeaderboard"
#endif
            );

        public static UnifiedLeaderboard NinjyLeaderboard
        {
            get { return s_ninjyLeaderboard; }
        }

        public static string GetPlatformID(string internalId)
        {
            return s_leaderboardDictionary.ContainsKey(internalId)
                ? s_leaderboardDictionary[internalId].ID
                : string.Empty;
        }

        private static readonly Dictionary<string, UnifiedLeaderboard> s_leaderboardDictionary = new Dictionary<string, UnifiedLeaderboard>
        {
            { "SpeedyLeaderboard", s_speedyLeaderboard },
            { "BombyLeaderboard", s_bombyLeaderboard },
            { "ShapeshiftyLeaderboard", s_shapeshiftyLeaderboard },
            { "NinjyLeaderboard", s_ninjyLeaderboard }
        };
    }
}
